// Flat config (ESLint 9). `eslint-config-expo` carries the React, React Hooks,
// React Native and TypeScript rules that match the Expo toolchain, so this only adds
// the ignore list on top.
const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      // Generated by drizzle-kit — regenerated wholesale by `npm run db:generate`,
      // so there's nothing to hand-fix in here.
      'src/db/migrations/**',
    ],
  },
];
