import type { Brew, BrewMethod, NewBrew } from '@/db/schema';

export type { Brew, NewBrew, BrewMethod };

/** Fields a caller may set when logging a brew. `id`/timestamps are generated by createBrew. */
export type CreateBrewInput = Omit<NewBrew, 'id' | 'createdAt' | 'updatedAt' | 'deletedAt'>;

/** Fields a caller may patch. `updatedAt` is stamped by updateBrew, never passed in. */
export type UpdateBrewInput = Partial<
  Omit<NewBrew, 'id' | 'createdAt' | 'updatedAt' | 'deletedAt'>
>;

export interface ListBrewsOptions {
  /** Matches against notes and grind text. */
  search?: string;
  method?: BrewMethod;
  /** Minimum rating (inclusive). */
  minRating?: number;
  /** Only brews with `brewed_at >=` this ISO timestamp. */
  since?: string;
  beanId?: string;
  limit?: number;
  offset?: number;
  /** Include soft-deleted rows. Defaults to false. */
  withDeleted?: boolean;
}
