import type { Bean, NewBean } from '@/db/schema';

export type { Bean, NewBean };

/** Fields a caller may set when adding a bag. `id`/timestamps are generated by createBean. */
export type CreateBeanInput = Omit<
  NewBean,
  'id' | 'createdAt' | 'updatedAt' | 'deletedAt' | 'currency' | 'isFinished'
> &
  Partial<Pick<NewBean, 'currency' | 'isFinished'>>;

/** Fields a caller may patch. `updatedAt` is stamped by updateBean, never passed in. */
export type UpdateBeanInput = Partial<
  Omit<NewBean, 'id' | 'createdAt' | 'updatedAt' | 'deletedAt'>
>;

export interface ListBeansOptions {
  /** Filter to active (false) or finished (true) bags. Omit for both. */
  finished?: boolean;
  /** Include soft-deleted rows. Defaults to false. */
  withDeleted?: boolean;
}

export interface BeanStats {
  brewCount: number;
  avgRating: number | null;
}
